[build]
  command = "pnpm install && pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_USE_PRODUCTION = "false"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
